replicaCount: 1

nameOverride: "cn-mqtt"

ingress:
  enabled: true
  hosts:
    - host: mqtt.cloudnesil.com
      paths:
        - ""

config: |-
  persistence true
  persistence_location /mosquitto/data/
  log_dest stdout
  listener 1884
  listener 1883
  protocol mqtt
  cafile /mosquitto/config/certs/ca.crt
  certfile /mosquitto/config/certs/server.crt
  keyfile /mosquitto/config/certs/server.key
  require_certificate true
  use_subject_as_username true

certs:
  ca:
    crt: |-
      -----BEGIN CERTIFICATE-----
      CA_CERT
      -----END CERTIFICATE-----
  server:
    crt: |-
      -----BEGIN CERTIFICATE-----
      SERVER_CERT
      -----END CERTIFICATE-----
    key: |-
      -----BEGIN PRIVATE KEY-----
      SERVER_KEY
      -----END PRIVATE KEY-----


## Persist data to a persistent volume
persistence:
  enabled: true
  storageClass: nfs

